import Head from 'next/head'
import Image from "next/image"

import { GetServerSidePropsContext } from 'next';

import { TopBar } from '@/components/TopBar';
import { Header } from '@/components/Header';
import { HomeHeroCategories } from '@/components/HomeHeroCategories';

import { Box, Container, Heading, SimpleGrid, Text } from '@chakra-ui/react'

import * as React from 'react';

import { Categories } from '@/models/Categories';
import { AdvantageSection } from '@/components/AdvantageSection';
import { groupProductByCategory, GroupedProducts } from '@/utils/groupProductByCategory';
import { HomeProductsGrid } from '@/components/HomeProductsGrid';

import bannerNewSeason from '/public/banner-new-season.jpg';
import bannerSale from '/public/banner-sale.jpg';
import { CenteredLabel } from '@/components/CenteredLabel';

export type Product = {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: {
    count: number;
    rate: number;
  };
}

type Props = {
  categories: Categories[],
  productsGroupedByCategory: GroupedProducts;
}


export default function Home({ categories, productsGroupedByCategory }: Props) {
  return (
    <>
      <Head>
        <title>eCommerce Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <TopBar />
      <Box marginBottom="2rem">
        <Header />
      </Box>
      <main>
        <Container size={{
          lg: 'lg'
        }}>
          <HomeHeroCategories categories={categories}></HomeHeroCategories>
          <AdvantageSection />
        </Container>
        
        <Container 
          maxW={{
            base: "100%",
            md: "1110px"
          }}
          paddingX="0"
        >
        {Object.entries(productsGroupedByCategory).map(([category, products]) => {
          return (
            <Box key={ category } marginBottom="4rem">
              <Heading 
                as="h2"
                size="md"
                textTransform="uppercase"
                margin={{
                  base: '0 0 1rem 1rem',
                  md: '0 0 2rem'
                }}>
                {category}
              </Heading>
              <HomeProductsGrid products={products} />
            </Box>
          );
          })}
        </Container>

        <Container size={{
          lg: 'lg'
        }}>
          <SimpleGrid 
            minChildWidth="255px"
            spacing={{
              base: '1rem',
              md: '2rem',
            }}
          >
            <Box position={"relative"}>
              <Image src={bannerNewSeason} alt="" />
              <Box position="absolute" left="50%" top="50%" transform="translate(-50%, -50%)">
                <CenteredLabel>
                  <Text fontSize="sm" color="gray.500">New Season</Text>
                  <Text fontSize="lg" fontWeight="bold" whiteSpace="nowrap">Lookbook collection</Text>
                </CenteredLabel>
              </Box>
            </Box>
            <Box position={"relative"}>
              <Image src={bannerSale} alt="" />
              <Box position="absolute" left="50%" top="50%" transform="translate(-50%, -50%)">
                <CenteredLabel>
                  <Text fontSize="sm" color="gray.500">Sale</Text>
                  <Text fontSize="lg" fontWeight="bold" whiteSpace="nowrap">Get up to {''}
                    <Text as="span" color="red">50% off</Text>
                  </Text>
                </CenteredLabel>
              </Box>
            </Box>
          </SimpleGrid>
        </Container>
      </main>
    </>
  )
}

export async function getServerSideProps(context: GetServerSidePropsContext) {

  const products = await fetch('https://fakestoreapi.com/products')
    .then(res => res.json());

  const categories = await fetch('https://fakestoreapi.com/products/categories')
    .then(res => res.json());

  const productsGroupedByCategory = groupProductByCategory(products);


  return {
    props: {
      products,
      categories,
      productsGroupedByCategory,
    },
  };
}