import Head from 'next/head'
import { GetServerSidePropsContext } from 'next';

import { TopBar } from '@/components/TopBar';
import { Header } from '@/components/Header';
import { HomeHeroCategories } from '@/components/HomeHeroCategories';

import { Box, Container, Grid, SimpleGrid } from '@chakra-ui/react'

import * as React from 'react';

import { Categories } from '@/models/Categories';
import { AdvantageSection } from '@/components/AdvantageSection';
import { groupProductByCategory, GroupedProducts } from '@/utils/groupProductByCategory';
import { HomeProductsGrid } from '@/components/HomeProductsGrid';

export type Product = {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: {
    count: number;
    rate: number;
  };
}

type Props = {
  products: Product[],
  categories: Categories[],
  productsGroupedByCategory: GroupedProducts;
}


export default function Home({ products, categories }: Props) {
  return (
    <>
      <Head>
        <title>eCommerce Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <TopBar />
      <Box marginBottom="2rem">
        <Header />
      </Box>
      <main>
        <Container size={{
          lg: 'lg'
        }}>
          <HomeHeroCategories categories={categories}></HomeHeroCategories>
          <AdvantageSection />
        </Container>
        
        <Container 
          maxW={{
            base: "100%",
            md: "1110px"
          }}
          paddingX="0"
        >
        <HomeProductsGrid products={products}></HomeProductsGrid>
        </Container>
      </main>
    </>
  )
}

export async function getServerSideProps(context: GetServerSidePropsContext) {

  const products = await fetch('https://fakestoreapi.com/products')
    .then(res => res.json())

  const categories = await fetch('https://fakestoreapi.com/products/categories')
    .then(res => res.json())

  const productsGroupedByCategory = groupProductByCategory(products);


  return {
    props: {
      products,
      categories
    }
  }
}